### ISSUE TITLE
Broken Invite Link

### ISSUE THREAD

**Issue by shanepaton** [LavenderFoxxo/fluff#2]
When clicking the bot invite link provided in README.MD, it points to [https://fluffbot.xyz/](https://fluffbot.xyz/) which throws an invalid certificate warning.

![image](https://user-images.githubusercontent.com/45543346/218285420-bb638c4b-9f9d-4493-b809-abfe3687c942.png)

When attempting to forcefully proceed, the browser returns ERR_HTTP2_PROTOCOL_ERROR.

![image](https://user-images.githubusercontent.com/45543346/218285451-721c364d-0b02-4980-beb2-cd1298ac5cf3.png)
Tested in Chrome Version 109.0.5414.120 (Official Build) (64-bit)
and Microsoft Edge Version 109.0.5414.120 (Official Build) (64-bit)
and Android Chrome Version 109.0.5414.117 on Android 13 for Pixel 4 XL

**Comment by lavylavenderr** [comment]
Site is now up and README.md is updated with a proper link.
